FROM debian:buster

RUN apt-get update
RUN apt install --no-install-recommends -qq -y curl ca-certificates

RUN curl -v https://packagecloud.io/install/repositories/coanda/public/script.deb.sh | bash

RUN apt install libdactl-1.0-dev -y
RUN apt remove libdactl-1.0-dev -y

RUN apt remove libdactl-1.0-0 -y
RUN apt install libdactl-1.0-0 -y
RUN apt remove libdactl-1.0-0 -y

RUN apt remove gir1.2-dactl-1.0 -y
RUN apt install gir1.2-dactl-1.0 -y
RUN apt remove gir1.2-dactl-1.0 -y

RUN apt remove dactl -y
RUN apt install dactl -y
RUN apt remove dactl -y
