#!/bin/bash

if [ $# -lt 1 ]
then
    echo "usage : $0 [core|ui|app]"
    exit
fi

case "$1" in
    app)
        vim src/dactl/dactl-main.vala \
            src/dactl/dactl-ui-application.vala \
            src/dactl/dactl-ui-application-view.vala \
            src/dactl/dactl-acquisition-settings.vala \
            src/dactl/dactl-application-controller.vala \
            src/dactl/dactl-application-factory.vala \
            src/dactl/dactl-application-model.vala \
            src/dactl/dactl-application-toolbar.vala \
            src/dactl/dactl-topbar.vala \
            src/dactl/dactl-configuration-editor.vala \
            src/dactl/dactl-configuration-toolbar.vala \
            src/dactl/dactl-sidebar.vala \
            src/dactl/dactl-settings.vala \
            src/dactl/dactl-settings-sidebar.vala \
            src/dactl/dactl-settings-toolbar.vala \
            src/dactl/dactl-control-settings.vala \
            src/dactl/dactl-general-settings.vala \
            src/dactl/dactl-log-settings.vala \
            src/dactl/dactl-plugin-settings.vala \
            src/dactl/dactl-ui-settings.vala
        ;;
    core)
        vim src/libdactl-core/dactl-buildable.vala \
            src/libdactl-core/dactl-cld-adapter.vala \
            src/libdactl-core/dactl-container.vala \
            src/libdactl-core/dactl-dbus-interface.vala \
            src/libdactl-core/dactl-factory.vala \
            src/libdactl-core/dactl-log-handler.vala \
            src/libdactl-core/dactl-module-loader.vala \
            src/libdactl-core/dactl-object.vala \
            src/libdactl-core/dactl-plugin-information.vala \
            src/libdactl-core/dactl-plugin-loader.vala \
            src/libdactl-core/dactl-plugin.vala
        ;;
    ui)
        vim src/libdactl-ui/dactl-ai-control.vala \
            src/libdactl-ui/dactl-ao-control.vala \
            src/libdactl-ui/dactl-box.vala \
            src/libdactl-ui/dactl-channel-treeview.vala \
            src/libdactl-ui/dactl-chart-axis.vala \
            src/libdactl-ui/dactl-chart.vala \
            src/libdactl-ui/dactl-chart-trace.vala \
            src/libdactl-ui/dactl-drawing.vala \
            src/libdactl-ui/dactl-exec-control.vala \
            src/libdactl-ui/dactl-log-control.vala \
            src/libdactl-ui/dactl-page.vala \
            src/libdactl-ui/dactl-pid-control.vala \
            src/libdactl-ui/dactl-pnid.vala \
            src/libdactl-ui/dactl-stripchart.vala \
            src/libdactl-ui/dactl-ui-factory.vala
        ;;
    *)
        echo "Invalid selection"
        ;;
esac
