/* dactl-cli-application.c generated by valac 0.30.0, the Vala compiler
 * generated from dactl-cli-application.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <dactl-core.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define DACTL_CLI_TYPE_APPLICATION (dactl_cli_application_get_type ())
#define DACTL_CLI_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication))
#define DACTL_CLI_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplicationClass))
#define DACTL_CLI_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DACTL_CLI_TYPE_APPLICATION))
#define DACTL_CLI_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DACTL_CLI_TYPE_APPLICATION))
#define DACTL_CLI_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplicationClass))

typedef struct _DactlCLIApplication DactlCLIApplication;
typedef struct _DactlCLIApplicationClass DactlCLIApplicationClass;
typedef struct _DactlCLIApplicationPrivate DactlCLIApplicationPrivate;

#define DACTL_CLI_APPLICATION_TYPE_COMMAND (dactl_cli_application_command_get_type ())
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _DactlCLIApplication {
	GApplication parent_instance;
	DactlCLIApplicationPrivate * priv;
	gboolean _admin;
};

struct _DactlCLIApplicationClass {
	GApplicationClass parent_class;
	gint (*launch) (DactlCLIApplication* self, gchar** args, int args_length1);
	DactlApplicationModel* (*get_model) (DactlCLIApplication* self);
	void (*set_model) (DactlCLIApplication* self, DactlApplicationModel* value);
	DactlApplicationView* (*get_view) (DactlCLIApplication* self);
	void (*set_view) (DactlCLIApplication* self, DactlApplicationView* value);
	DactlApplicationController* (*get_controller) (DactlCLIApplication* self);
	void (*set_controller) (DactlCLIApplication* self, DactlApplicationController* value);
	GeeArrayList* (*get_plugins) (DactlCLIApplication* self);
	void (*set_plugins) (DactlCLIApplication* self, GeeArrayList* value);
};

struct _DactlCLIApplicationPrivate {
	DactlApplicationModel* _model;
	DactlApplicationView* _view;
	DactlApplicationController* _controller;
	GeeArrayList* _plugins;
};

typedef enum  {
	DACTL_CLI_APPLICATION_COMMAND_NONE,
	DACTL_CLI_APPLICATION_COMMAND_CLD,
	DACTL_CLI_APPLICATION_COMMAND_CONFIG,
	DACTL_CLI_APPLICATION_COMMAND_CONTROL,
	DACTL_CLI_APPLICATION_COMMAND_HELP,
	DACTL_CLI_APPLICATION_COMMAND_LIST,
	DACTL_CLI_APPLICATION_COMMAND_LOG,
	DACTL_CLI_APPLICATION_COMMAND_READ,
	DACTL_CLI_APPLICATION_COMMAND_WRITE,
	DACTL_CLI_APPLICATION_COMMAND_QUIT
} DactlCLIApplicationCommand;


static gpointer dactl_cli_application_parent_class = NULL;
static GOnce dactl_cli_application__instance;
static GOnce dactl_cli_application__instance = G_ONCE_INIT;
static DactlApplicationIface* dactl_cli_application_dactl_application_parent_iface = NULL;

GType dactl_cli_application_get_type (void) G_GNUC_CONST;
#define DACTL_CLI_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplicationPrivate))
enum  {
	DACTL_CLI_APPLICATION_DUMMY_PROPERTY,
	DACTL_CLI_APPLICATION_ADMIN,
	DACTL_CLI_APPLICATION_MODEL,
	DACTL_CLI_APPLICATION_VIEW,
	DACTL_CLI_APPLICATION_CONTROLLER,
	DACTL_CLI_APPLICATION_PLUGINS
};
GType dactl_cli_application_command_get_type (void) G_GNUC_CONST;
gchar* dactl_cli_application_command_to_string (DactlCLIApplicationCommand self);
gchar* dactl_cli_application_command_description (DactlCLIApplicationCommand self);
DactlCLIApplicationCommand* dactl_cli_application_command_all (int* result_length1);
DactlCLIApplicationCommand dactl_cli_application_command_parse (const gchar* value);
DactlCLIApplication* dactl_cli_application_get_default (void);
static DactlCLIApplication* __lambda4_ (void);
DactlCLIApplication* dactl_cli_application_new (void);
DactlCLIApplication* dactl_cli_application_construct (GType object_type);
static gpointer ___lambda4__gthread_func (gpointer self);
void dactl_cli_application_set_plugins (DactlCLIApplication* self, GeeArrayList* value);
static void dactl_cli_application_real_register_plugin (DactlApplication* base, DactlPlugin* plugin);
gint dactl_cli_application_launch (DactlCLIApplication* self, gchar** args, int args_length1);
static gint dactl_cli_application_real_launch (DactlCLIApplication* self, gchar** args, int args_length1);
gboolean dactl_cli_application_get_admin (DactlCLIApplication* self);
void dactl_cli_application_set_admin (DactlCLIApplication* self, gboolean value);
DactlApplicationModel* dactl_cli_application_get_model (DactlCLIApplication* self);
void dactl_cli_application_set_model (DactlCLIApplication* self, DactlApplicationModel* value);
DactlApplicationView* dactl_cli_application_get_view (DactlCLIApplication* self);
void dactl_cli_application_set_view (DactlCLIApplication* self, DactlApplicationView* value);
DactlApplicationController* dactl_cli_application_get_controller (DactlCLIApplication* self);
void dactl_cli_application_set_controller (DactlCLIApplication* self, DactlApplicationController* value);
GeeArrayList* dactl_cli_application_get_plugins (DactlCLIApplication* self);
static void dactl_cli_application_finalize (GObject* obj);
static void _vala_dactl_cli_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_dactl_cli_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


gchar* dactl_cli_application_command_to_string (DactlCLIApplicationCommand self) {
	gchar* result = NULL;
	switch (self) {
		case DACTL_CLI_APPLICATION_COMMAND_NONE:
		{
			gchar* _tmp0_ = NULL;
			_tmp0_ = g_strdup ("none");
			result = _tmp0_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_CLD:
		{
			gchar* _tmp1_ = NULL;
			_tmp1_ = g_strdup ("cld");
			result = _tmp1_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_CONFIG:
		{
			gchar* _tmp2_ = NULL;
			_tmp2_ = g_strdup ("config");
			result = _tmp2_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_CONTROL:
		{
			gchar* _tmp3_ = NULL;
			_tmp3_ = g_strdup ("control");
			result = _tmp3_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_HELP:
		{
			gchar* _tmp4_ = NULL;
			_tmp4_ = g_strdup ("help");
			result = _tmp4_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_LIST:
		{
			gchar* _tmp5_ = NULL;
			_tmp5_ = g_strdup ("list");
			result = _tmp5_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_LOG:
		{
			gchar* _tmp6_ = NULL;
			_tmp6_ = g_strdup ("log");
			result = _tmp6_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_READ:
		{
			gchar* _tmp7_ = NULL;
			_tmp7_ = g_strdup ("read");
			result = _tmp7_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_WRITE:
		{
			gchar* _tmp8_ = NULL;
			_tmp8_ = g_strdup ("write");
			result = _tmp8_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_QUIT:
		{
			gchar* _tmp9_ = NULL;
			_tmp9_ = g_strdup ("quit");
			result = _tmp9_;
			return result;
		}
		default:
		{
			g_assert_not_reached ();
		}
	}
}


gchar* dactl_cli_application_command_description (DactlCLIApplicationCommand self) {
	gchar* result = NULL;
	switch (self) {
		case DACTL_CLI_APPLICATION_COMMAND_NONE:
		{
			gchar* _tmp0_ = NULL;
			_tmp0_ = g_strdup ("No operation");
			result = _tmp0_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_CLD:
		{
			gchar* _tmp1_ = NULL;
			_tmp1_ = g_strdup ("Interface with the application CLD object tree");
			result = _tmp1_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_CONFIG:
		{
			gchar* _tmp2_ = NULL;
			_tmp2_ = g_strdup ("Perform an operation with the configuration");
			result = _tmp2_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_CONTROL:
		{
			gchar* _tmp3_ = NULL;
			_tmp3_ = g_strdup ("Perform a control operation");
			result = _tmp3_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_HELP:
		{
			gchar* _tmp4_ = NULL;
			_tmp4_ = g_strdup ("Show the help for a command");
			result = _tmp4_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_LIST:
		{
			gchar* _tmp5_ = NULL;
			_tmp5_ = g_strdup ("List all available commands");
			result = _tmp5_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_LOG:
		{
			gchar* _tmp6_ = NULL;
			_tmp6_ = g_strdup ("Perform a logging operation");
			result = _tmp6_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_READ:
		{
			gchar* _tmp7_ = NULL;
			_tmp7_ = g_strdup ("Read one or more channels");
			result = _tmp7_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_WRITE:
		{
			gchar* _tmp8_ = NULL;
			_tmp8_ = g_strdup ("Write one or more channels");
			result = _tmp8_;
			return result;
		}
		case DACTL_CLI_APPLICATION_COMMAND_QUIT:
		{
			gchar* _tmp9_ = NULL;
			_tmp9_ = g_strdup ("Quit the command line interface");
			result = _tmp9_;
			return result;
		}
		default:
		{
			g_assert_not_reached ();
		}
	}
}


DactlCLIApplicationCommand* dactl_cli_application_command_all (int* result_length1) {
	DactlCLIApplicationCommand* result = NULL;
	DactlCLIApplicationCommand* _tmp0_ = NULL;
	DactlCLIApplicationCommand* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	_tmp0_ = g_new0 (DactlCLIApplicationCommand, 10);
	_tmp0_[0] = DACTL_CLI_APPLICATION_COMMAND_NONE;
	_tmp0_[1] = DACTL_CLI_APPLICATION_COMMAND_CLD;
	_tmp0_[2] = DACTL_CLI_APPLICATION_COMMAND_CONFIG;
	_tmp0_[3] = DACTL_CLI_APPLICATION_COMMAND_CONTROL;
	_tmp0_[4] = DACTL_CLI_APPLICATION_COMMAND_HELP;
	_tmp0_[5] = DACTL_CLI_APPLICATION_COMMAND_LIST;
	_tmp0_[6] = DACTL_CLI_APPLICATION_COMMAND_LOG;
	_tmp0_[7] = DACTL_CLI_APPLICATION_COMMAND_READ;
	_tmp0_[8] = DACTL_CLI_APPLICATION_COMMAND_WRITE;
	_tmp0_[9] = DACTL_CLI_APPLICATION_COMMAND_QUIT;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = 10;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


DactlCLIApplicationCommand dactl_cli_application_command_parse (const gchar* value) {
	DactlCLIApplicationCommand result = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (value != NULL, 0);
	{
		GRegex* regex_none = NULL;
		GRegex* _tmp0_ = NULL;
		GRegex* regex_cld = NULL;
		GRegex* _tmp1_ = NULL;
		GRegex* regex_config = NULL;
		GRegex* _tmp2_ = NULL;
		GRegex* regex_control = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* regex_help = NULL;
		GRegex* _tmp4_ = NULL;
		GRegex* regex_list = NULL;
		GRegex* _tmp5_ = NULL;
		GRegex* regex_log = NULL;
		GRegex* _tmp6_ = NULL;
		GRegex* regex_read = NULL;
		GRegex* _tmp7_ = NULL;
		GRegex* regex_write = NULL;
		GRegex* _tmp8_ = NULL;
		GRegex* regex_quit = NULL;
		GRegex* _tmp9_ = NULL;
		GRegex* _tmp10_ = NULL;
		const gchar* _tmp11_ = NULL;
		gboolean _tmp12_ = FALSE;
		_tmp0_ = g_regex_new ("none", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_none = _tmp0_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp1_ = g_regex_new ("cld", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_cld = _tmp1_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp2_ = g_regex_new ("c|cfg|config", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_config = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp3_ = g_regex_new ("ctl|control", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_control = _tmp3_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp4_ = g_regex_new ("h|help", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_help = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp5_ = g_regex_new ("ls|list", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_list = _tmp5_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp6_ = g_regex_new ("l|log", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_log = _tmp6_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp7_ = g_regex_new ("r|read", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_read = _tmp7_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp8_ = g_regex_new ("w|write", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_write = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_read);
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_read);
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp9_ = g_regex_new ("q|quit", G_REGEX_CASELESS, 0, &_inner_error_);
		regex_quit = _tmp9_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex_write);
			_g_regex_unref0 (regex_read);
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex_write);
			_g_regex_unref0 (regex_read);
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_tmp10_ = regex_none;
		_tmp11_ = value;
		_tmp12_ = g_regex_match (_tmp10_, _tmp11_, 0, NULL);
		if (_tmp12_) {
			result = DACTL_CLI_APPLICATION_COMMAND_NONE;
			_g_regex_unref0 (regex_quit);
			_g_regex_unref0 (regex_write);
			_g_regex_unref0 (regex_read);
			_g_regex_unref0 (regex_log);
			_g_regex_unref0 (regex_list);
			_g_regex_unref0 (regex_help);
			_g_regex_unref0 (regex_control);
			_g_regex_unref0 (regex_config);
			_g_regex_unref0 (regex_cld);
			_g_regex_unref0 (regex_none);
			return result;
		} else {
			GRegex* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			gboolean _tmp15_ = FALSE;
			_tmp13_ = regex_cld;
			_tmp14_ = value;
			_tmp15_ = g_regex_match (_tmp13_, _tmp14_, 0, NULL);
			if (_tmp15_) {
				result = DACTL_CLI_APPLICATION_COMMAND_CLD;
				_g_regex_unref0 (regex_quit);
				_g_regex_unref0 (regex_write);
				_g_regex_unref0 (regex_read);
				_g_regex_unref0 (regex_log);
				_g_regex_unref0 (regex_list);
				_g_regex_unref0 (regex_help);
				_g_regex_unref0 (regex_control);
				_g_regex_unref0 (regex_config);
				_g_regex_unref0 (regex_cld);
				_g_regex_unref0 (regex_none);
				return result;
			} else {
				GRegex* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				gboolean _tmp18_ = FALSE;
				_tmp16_ = regex_config;
				_tmp17_ = value;
				_tmp18_ = g_regex_match (_tmp16_, _tmp17_, 0, NULL);
				if (_tmp18_) {
					result = DACTL_CLI_APPLICATION_COMMAND_CONFIG;
					_g_regex_unref0 (regex_quit);
					_g_regex_unref0 (regex_write);
					_g_regex_unref0 (regex_read);
					_g_regex_unref0 (regex_log);
					_g_regex_unref0 (regex_list);
					_g_regex_unref0 (regex_help);
					_g_regex_unref0 (regex_control);
					_g_regex_unref0 (regex_config);
					_g_regex_unref0 (regex_cld);
					_g_regex_unref0 (regex_none);
					return result;
				} else {
					GRegex* _tmp19_ = NULL;
					const gchar* _tmp20_ = NULL;
					gboolean _tmp21_ = FALSE;
					_tmp19_ = regex_control;
					_tmp20_ = value;
					_tmp21_ = g_regex_match (_tmp19_, _tmp20_, 0, NULL);
					if (_tmp21_) {
						result = DACTL_CLI_APPLICATION_COMMAND_CONTROL;
						_g_regex_unref0 (regex_quit);
						_g_regex_unref0 (regex_write);
						_g_regex_unref0 (regex_read);
						_g_regex_unref0 (regex_log);
						_g_regex_unref0 (regex_list);
						_g_regex_unref0 (regex_help);
						_g_regex_unref0 (regex_control);
						_g_regex_unref0 (regex_config);
						_g_regex_unref0 (regex_cld);
						_g_regex_unref0 (regex_none);
						return result;
					} else {
						GRegex* _tmp22_ = NULL;
						const gchar* _tmp23_ = NULL;
						gboolean _tmp24_ = FALSE;
						_tmp22_ = regex_help;
						_tmp23_ = value;
						_tmp24_ = g_regex_match (_tmp22_, _tmp23_, 0, NULL);
						if (_tmp24_) {
							result = DACTL_CLI_APPLICATION_COMMAND_HELP;
							_g_regex_unref0 (regex_quit);
							_g_regex_unref0 (regex_write);
							_g_regex_unref0 (regex_read);
							_g_regex_unref0 (regex_log);
							_g_regex_unref0 (regex_list);
							_g_regex_unref0 (regex_help);
							_g_regex_unref0 (regex_control);
							_g_regex_unref0 (regex_config);
							_g_regex_unref0 (regex_cld);
							_g_regex_unref0 (regex_none);
							return result;
						} else {
							GRegex* _tmp25_ = NULL;
							const gchar* _tmp26_ = NULL;
							gboolean _tmp27_ = FALSE;
							_tmp25_ = regex_list;
							_tmp26_ = value;
							_tmp27_ = g_regex_match (_tmp25_, _tmp26_, 0, NULL);
							if (_tmp27_) {
								result = DACTL_CLI_APPLICATION_COMMAND_LIST;
								_g_regex_unref0 (regex_quit);
								_g_regex_unref0 (regex_write);
								_g_regex_unref0 (regex_read);
								_g_regex_unref0 (regex_log);
								_g_regex_unref0 (regex_list);
								_g_regex_unref0 (regex_help);
								_g_regex_unref0 (regex_control);
								_g_regex_unref0 (regex_config);
								_g_regex_unref0 (regex_cld);
								_g_regex_unref0 (regex_none);
								return result;
							} else {
								GRegex* _tmp28_ = NULL;
								const gchar* _tmp29_ = NULL;
								gboolean _tmp30_ = FALSE;
								_tmp28_ = regex_log;
								_tmp29_ = value;
								_tmp30_ = g_regex_match (_tmp28_, _tmp29_, 0, NULL);
								if (_tmp30_) {
									result = DACTL_CLI_APPLICATION_COMMAND_LOG;
									_g_regex_unref0 (regex_quit);
									_g_regex_unref0 (regex_write);
									_g_regex_unref0 (regex_read);
									_g_regex_unref0 (regex_log);
									_g_regex_unref0 (regex_list);
									_g_regex_unref0 (regex_help);
									_g_regex_unref0 (regex_control);
									_g_regex_unref0 (regex_config);
									_g_regex_unref0 (regex_cld);
									_g_regex_unref0 (regex_none);
									return result;
								} else {
									GRegex* _tmp31_ = NULL;
									const gchar* _tmp32_ = NULL;
									gboolean _tmp33_ = FALSE;
									_tmp31_ = regex_read;
									_tmp32_ = value;
									_tmp33_ = g_regex_match (_tmp31_, _tmp32_, 0, NULL);
									if (_tmp33_) {
										result = DACTL_CLI_APPLICATION_COMMAND_READ;
										_g_regex_unref0 (regex_quit);
										_g_regex_unref0 (regex_write);
										_g_regex_unref0 (regex_read);
										_g_regex_unref0 (regex_log);
										_g_regex_unref0 (regex_list);
										_g_regex_unref0 (regex_help);
										_g_regex_unref0 (regex_control);
										_g_regex_unref0 (regex_config);
										_g_regex_unref0 (regex_cld);
										_g_regex_unref0 (regex_none);
										return result;
									} else {
										GRegex* _tmp34_ = NULL;
										const gchar* _tmp35_ = NULL;
										gboolean _tmp36_ = FALSE;
										_tmp34_ = regex_write;
										_tmp35_ = value;
										_tmp36_ = g_regex_match (_tmp34_, _tmp35_, 0, NULL);
										if (_tmp36_) {
											result = DACTL_CLI_APPLICATION_COMMAND_WRITE;
											_g_regex_unref0 (regex_quit);
											_g_regex_unref0 (regex_write);
											_g_regex_unref0 (regex_read);
											_g_regex_unref0 (regex_log);
											_g_regex_unref0 (regex_list);
											_g_regex_unref0 (regex_help);
											_g_regex_unref0 (regex_control);
											_g_regex_unref0 (regex_config);
											_g_regex_unref0 (regex_cld);
											_g_regex_unref0 (regex_none);
											return result;
										} else {
											GRegex* _tmp37_ = NULL;
											const gchar* _tmp38_ = NULL;
											gboolean _tmp39_ = FALSE;
											_tmp37_ = regex_quit;
											_tmp38_ = value;
											_tmp39_ = g_regex_match (_tmp37_, _tmp38_, 0, NULL);
											if (_tmp39_) {
												result = DACTL_CLI_APPLICATION_COMMAND_QUIT;
												_g_regex_unref0 (regex_quit);
												_g_regex_unref0 (regex_write);
												_g_regex_unref0 (regex_read);
												_g_regex_unref0 (regex_log);
												_g_regex_unref0 (regex_list);
												_g_regex_unref0 (regex_help);
												_g_regex_unref0 (regex_control);
												_g_regex_unref0 (regex_config);
												_g_regex_unref0 (regex_cld);
												_g_regex_unref0 (regex_none);
												return result;
											} else {
												result = DACTL_CLI_APPLICATION_COMMAND_NONE;
												_g_regex_unref0 (regex_quit);
												_g_regex_unref0 (regex_write);
												_g_regex_unref0 (regex_read);
												_g_regex_unref0 (regex_log);
												_g_regex_unref0 (regex_list);
												_g_regex_unref0 (regex_help);
												_g_regex_unref0 (regex_control);
												_g_regex_unref0 (regex_config);
												_g_regex_unref0 (regex_cld);
												_g_regex_unref0 (regex_none);
												return result;
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
		_g_regex_unref0 (regex_quit);
		_g_regex_unref0 (regex_write);
		_g_regex_unref0 (regex_read);
		_g_regex_unref0 (regex_log);
		_g_regex_unref0 (regex_list);
		_g_regex_unref0 (regex_help);
		_g_regex_unref0 (regex_control);
		_g_regex_unref0 (regex_config);
		_g_regex_unref0 (regex_cld);
		_g_regex_unref0 (regex_none);
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		GError* e = NULL;
		GError* _tmp40_ = NULL;
		const gchar* _tmp41_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp40_ = e;
		_tmp41_ = _tmp40_->message;
		g_message ("dactl-cli-application.vala:106: Command regex error: %s", _tmp41_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = DACTL_CLI_APPLICATION_COMMAND_NONE;
	return result;
}


/**
     * The commands that are recognized.
     */
GType dactl_cli_application_command_get_type (void) {
	static volatile gsize dactl_cli_application_command_type_id__volatile = 0;
	if (g_once_init_enter (&dactl_cli_application_command_type_id__volatile)) {
		static const GEnumValue values[] = {{DACTL_CLI_APPLICATION_COMMAND_NONE, "DACTL_CLI_APPLICATION_COMMAND_NONE", "none"}, {DACTL_CLI_APPLICATION_COMMAND_CLD, "DACTL_CLI_APPLICATION_COMMAND_CLD", "cld"}, {DACTL_CLI_APPLICATION_COMMAND_CONFIG, "DACTL_CLI_APPLICATION_COMMAND_CONFIG", "config"}, {DACTL_CLI_APPLICATION_COMMAND_CONTROL, "DACTL_CLI_APPLICATION_COMMAND_CONTROL", "control"}, {DACTL_CLI_APPLICATION_COMMAND_HELP, "DACTL_CLI_APPLICATION_COMMAND_HELP", "help"}, {DACTL_CLI_APPLICATION_COMMAND_LIST, "DACTL_CLI_APPLICATION_COMMAND_LIST", "list"}, {DACTL_CLI_APPLICATION_COMMAND_LOG, "DACTL_CLI_APPLICATION_COMMAND_LOG", "log"}, {DACTL_CLI_APPLICATION_COMMAND_READ, "DACTL_CLI_APPLICATION_COMMAND_READ", "read"}, {DACTL_CLI_APPLICATION_COMMAND_WRITE, "DACTL_CLI_APPLICATION_COMMAND_WRITE", "write"}, {DACTL_CLI_APPLICATION_COMMAND_QUIT, "DACTL_CLI_APPLICATION_COMMAND_QUIT", "quit"}, {0, NULL, NULL}};
		GType dactl_cli_application_command_type_id;
		dactl_cli_application_command_type_id = g_enum_register_static ("DactlCLIApplicationCommand", values);
		g_once_init_leave (&dactl_cli_application_command_type_id__volatile, dactl_cli_application_command_type_id);
	}
	return dactl_cli_application_command_type_id__volatile;
}


/**
     * Instantiate a new command line application.
     *
     * @return Instance of the application.
     */
static DactlCLIApplication* __lambda4_ (void) {
	DactlCLIApplication* result = NULL;
	DactlCLIApplication* _tmp0_ = NULL;
	_tmp0_ = dactl_cli_application_new ();
	result = _tmp0_;
	return result;
}


static gpointer ___lambda4__gthread_func (gpointer self) {
	gpointer result;
	result = __lambda4_ ();
	return result;
}


DactlCLIApplication* dactl_cli_application_get_default (void) {
	DactlCLIApplication* result = NULL;
	gconstpointer _tmp0_ = NULL;
	_tmp0_ = g_once (&dactl_cli_application__instance, ___lambda4__gthread_func, NULL);
	result = (DactlCLIApplication*) _tmp0_;
	return result;
}


DactlCLIApplication* dactl_cli_application_construct (GType object_type) {
	DactlCLIApplication * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_debug ("dactl-cli-application.vala:163: CLI application construction");
	self = (DactlCLIApplication*) g_object_new (object_type, "application-id", "org.coanda.dactl.cli", "flags", G_APPLICATION_HANDLES_COMMAND_LINE | G_APPLICATION_HANDLES_OPEN, NULL);
	_tmp0_ = gee_array_list_new (DACTL_TYPE_PLUGIN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_tmp1_ = _tmp0_;
	dactl_cli_application_set_plugins (self, _tmp1_);
	_g_object_unref0 (_tmp1_);
	return self;
}


DactlCLIApplication* dactl_cli_application_new (void) {
	return dactl_cli_application_construct (DACTL_CLI_TYPE_APPLICATION);
}


/**
     * {@inheritDoc}
     */
static void dactl_cli_application_real_register_plugin (DactlApplication* base, DactlPlugin* plugin) {
	DactlCLIApplication * self;
	self = (DactlCLIApplication*) base;
	g_return_if_fail (plugin != NULL);
}


/**
     * {@inheritDoc}
     */
static gint dactl_cli_application_real_launch (DactlCLIApplication* self, gchar** args, int args_length1) {
	gint result = 0;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp1_ = g_application_run (G_TYPE_CHECK_INSTANCE_TYPE (self, g_application_get_type ()) ? ((GApplication*) self) : NULL, _tmp0__length1, _tmp0_);
	result = _tmp1_;
	return result;
}


gint dactl_cli_application_launch (DactlCLIApplication* self, gchar** args, int args_length1) {
	g_return_val_if_fail (self != NULL, 0);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->launch (self, args, args_length1);
}


gboolean dactl_cli_application_get_admin (DactlCLIApplication* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->_admin;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_admin (DactlCLIApplication* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_admin = _tmp0_;
	g_object_notify ((GObject *) self, "admin");
}


DactlApplicationModel* dactl_cli_application_get_model (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_model (self);
}


static DactlApplicationModel* dactl_cli_application_real_get_model (DactlCLIApplication* base) {
	DactlApplicationModel* result;
	DactlCLIApplication* self;
	DactlApplicationModel* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_model;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_model (DactlCLIApplication* self, DactlApplicationModel* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_model (self, value);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void dactl_cli_application_real_set_model (DactlCLIApplication* base, DactlApplicationModel* value) {
	DactlCLIApplication* self;
	DactlApplicationModel* _tmp0_ = NULL;
	DactlApplicationModel* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_model);
	self->priv->_model = _tmp1_;
	g_object_notify ((GObject *) self, "model");
}


DactlApplicationView* dactl_cli_application_get_view (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_view (self);
}


static DactlApplicationView* dactl_cli_application_real_get_view (DactlCLIApplication* base) {
	DactlApplicationView* result;
	DactlCLIApplication* self;
	DactlApplicationView* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_view;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_view (DactlCLIApplication* self, DactlApplicationView* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_view (self, value);
}


static void dactl_cli_application_real_set_view (DactlCLIApplication* base, DactlApplicationView* value) {
	DactlCLIApplication* self;
	DactlApplicationView* _tmp0_ = NULL;
	DactlApplicationView* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_view);
	self->priv->_view = _tmp1_;
	g_object_notify ((GObject *) self, "view");
}


DactlApplicationController* dactl_cli_application_get_controller (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_controller (self);
}


static DactlApplicationController* dactl_cli_application_real_get_controller (DactlCLIApplication* base) {
	DactlApplicationController* result;
	DactlCLIApplication* self;
	DactlApplicationController* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_controller;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_controller (DactlCLIApplication* self, DactlApplicationController* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_controller (self, value);
}


static void dactl_cli_application_real_set_controller (DactlCLIApplication* base, DactlApplicationController* value) {
	DactlCLIApplication* self;
	DactlApplicationController* _tmp0_ = NULL;
	DactlApplicationController* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_controller);
	self->priv->_controller = _tmp1_;
	g_object_notify ((GObject *) self, "controller");
}


GeeArrayList* dactl_cli_application_get_plugins (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_plugins (self);
}


static GeeArrayList* dactl_cli_application_real_get_plugins (DactlCLIApplication* base) {
	GeeArrayList* result;
	DactlCLIApplication* self;
	GeeArrayList* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_plugins;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_plugins (DactlCLIApplication* self, GeeArrayList* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_plugins (self, value);
}


static void dactl_cli_application_real_set_plugins (DactlCLIApplication* base, GeeArrayList* value) {
	DactlCLIApplication* self;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_plugins);
	self->priv->_plugins = _tmp1_;
	g_object_notify ((GObject *) self, "plugins");
}


static void dactl_cli_application_class_init (DactlCLIApplicationClass * klass) {
	dactl_cli_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DactlCLIApplicationPrivate));
	((DactlCLIApplicationClass *) klass)->launch = dactl_cli_application_real_launch;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_model = dactl_cli_application_real_get_model;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_model = dactl_cli_application_real_set_model;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_view = dactl_cli_application_real_get_view;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_view = dactl_cli_application_real_set_view;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_controller = dactl_cli_application_real_get_controller;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_controller = dactl_cli_application_real_set_controller;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_plugins = dactl_cli_application_real_get_plugins;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_plugins = dactl_cli_application_real_set_plugins;
	G_OBJECT_CLASS (klass)->get_property = _vala_dactl_cli_application_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_dactl_cli_application_set_property;
	G_OBJECT_CLASS (klass)->finalize = dactl_cli_application_finalize;
	/**
	     * Allow administrative functionality
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_ADMIN, g_param_spec_boolean ("admin", "admin", "admin", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_MODEL, g_param_spec_object ("model", "model", "model", DACTL_TYPE_APPLICATION_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_VIEW, g_param_spec_object ("view", "view", "view", DACTL_TYPE_APPLICATION_VIEW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", DACTL_TYPE_APPLICATION_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_PLUGINS, g_param_spec_object ("plugins", "plugins", "plugins", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * Used when the user requests a configuration save.
	     */
	g_signal_new ("save_requested", DACTL_CLI_TYPE_APPLICATION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void dactl_cli_application_dactl_application_interface_init (DactlApplicationIface * iface) {
	dactl_cli_application_dactl_application_parent_iface = g_type_interface_peek_parent (iface);
	iface->register_plugin = (void (*)(DactlApplication*, DactlPlugin*)) dactl_cli_application_real_register_plugin;
	iface->launch = (gint (*)(DactlApplication*, gchar**, int)) dactl_cli_application_launch;
	iface->get_model = (DactlApplicationModel* (*) (DactlApplication *)) dactl_cli_application_get_model;
	iface->set_model = (void (*) (DactlApplication *, DactlApplicationModel*)) dactl_cli_application_set_model;
	iface->get_view = (DactlApplicationView* (*) (DactlApplication *)) dactl_cli_application_get_view;
	iface->set_view = (void (*) (DactlApplication *, DactlApplicationView*)) dactl_cli_application_set_view;
	iface->get_controller = (DactlApplicationController* (*) (DactlApplication *)) dactl_cli_application_get_controller;
	iface->set_controller = (void (*) (DactlApplication *, DactlApplicationController*)) dactl_cli_application_set_controller;
	iface->get_plugins = (GeeArrayList* (*) (DactlApplication *)) dactl_cli_application_get_plugins;
	iface->set_plugins = (void (*) (DactlApplication *, GeeArrayList*)) dactl_cli_application_set_plugins;
}


static void dactl_cli_application_instance_init (DactlCLIApplication * self) {
	self->priv = DACTL_CLI_APPLICATION_GET_PRIVATE (self);
	self->_admin = FALSE;
}


static void dactl_cli_application_finalize (GObject* obj) {
	DactlCLIApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication);
	_g_object_unref0 (self->priv->_model);
	_g_object_unref0 (self->priv->_view);
	_g_object_unref0 (self->priv->_controller);
	_g_object_unref0 (self->priv->_plugins);
	G_OBJECT_CLASS (dactl_cli_application_parent_class)->finalize (obj);
}


GType dactl_cli_application_get_type (void) {
	static volatile gsize dactl_cli_application_type_id__volatile = 0;
	if (g_once_init_enter (&dactl_cli_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DactlCLIApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dactl_cli_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DactlCLIApplication), 0, (GInstanceInitFunc) dactl_cli_application_instance_init, NULL };
		static const GInterfaceInfo dactl_application_info = { (GInterfaceInitFunc) dactl_cli_application_dactl_application_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType dactl_cli_application_type_id;
		dactl_cli_application_type_id = g_type_register_static (g_application_get_type (), "DactlCLIApplication", &g_define_type_info, 0);
		g_type_add_interface_static (dactl_cli_application_type_id, DACTL_TYPE_APPLICATION, &dactl_application_info);
		g_once_init_leave (&dactl_cli_application_type_id__volatile, dactl_cli_application_type_id);
	}
	return dactl_cli_application_type_id__volatile;
}


static void _vala_dactl_cli_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DactlCLIApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication);
	switch (property_id) {
		case DACTL_CLI_APPLICATION_ADMIN:
		g_value_set_boolean (value, dactl_cli_application_get_admin (self));
		break;
		case DACTL_CLI_APPLICATION_MODEL:
		g_value_set_object (value, dactl_cli_application_get_model (self));
		break;
		case DACTL_CLI_APPLICATION_VIEW:
		g_value_set_object (value, dactl_cli_application_get_view (self));
		break;
		case DACTL_CLI_APPLICATION_CONTROLLER:
		g_value_set_object (value, dactl_cli_application_get_controller (self));
		break;
		case DACTL_CLI_APPLICATION_PLUGINS:
		g_value_set_object (value, dactl_cli_application_get_plugins (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_dactl_cli_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DactlCLIApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication);
	switch (property_id) {
		case DACTL_CLI_APPLICATION_ADMIN:
		dactl_cli_application_set_admin (self, g_value_get_boolean (value));
		break;
		case DACTL_CLI_APPLICATION_MODEL:
		dactl_cli_application_set_model (self, g_value_get_object (value));
		break;
		case DACTL_CLI_APPLICATION_VIEW:
		dactl_cli_application_set_view (self, g_value_get_object (value));
		break;
		case DACTL_CLI_APPLICATION_CONTROLLER:
		dactl_cli_application_set_controller (self, g_value_get_object (value));
		break;
		case DACTL_CLI_APPLICATION_PLUGINS:
		dactl_cli_application_set_plugins (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



