/* dactl-cli-application.c generated by valac 0.30.0, the Vala compiler
 * generated from dactl-cli-application.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <dactl-core.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define DACTL_CLI_TYPE_APPLICATION (dactl_cli_application_get_type ())
#define DACTL_CLI_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication))
#define DACTL_CLI_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplicationClass))
#define DACTL_CLI_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DACTL_CLI_TYPE_APPLICATION))
#define DACTL_CLI_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DACTL_CLI_TYPE_APPLICATION))
#define DACTL_CLI_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplicationClass))

typedef struct _DactlCLIApplication DactlCLIApplication;
typedef struct _DactlCLIApplicationClass DactlCLIApplicationClass;
typedef struct _DactlCLIApplicationPrivate DactlCLIApplicationPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _DactlCLIApplication {
	GApplication parent_instance;
	DactlCLIApplicationPrivate * priv;
	gboolean _admin;
};

struct _DactlCLIApplicationClass {
	GApplicationClass parent_class;
	gint (*launch) (DactlCLIApplication* self, gchar** args, int args_length1);
	DactlApplicationModel* (*get_model) (DactlCLIApplication* self);
	void (*set_model) (DactlCLIApplication* self, DactlApplicationModel* value);
	DactlApplicationView* (*get_view) (DactlCLIApplication* self);
	void (*set_view) (DactlCLIApplication* self, DactlApplicationView* value);
	DactlApplicationController* (*get_controller) (DactlCLIApplication* self);
	void (*set_controller) (DactlCLIApplication* self, DactlApplicationController* value);
	GeeArrayList* (*get_plugins) (DactlCLIApplication* self);
	void (*set_plugins) (DactlCLIApplication* self, GeeArrayList* value);
};

struct _DactlCLIApplicationPrivate {
	DactlApplicationModel* _model;
	DactlApplicationView* _view;
	DactlApplicationController* _controller;
	GeeArrayList* _plugins;
};


static gpointer dactl_cli_application_parent_class = NULL;
static GOnce dactl_cli_application__instance;
static GOnce dactl_cli_application__instance = G_ONCE_INIT;
static DactlApplicationIface* dactl_cli_application_dactl_application_parent_iface = NULL;

GType dactl_cli_application_get_type (void) G_GNUC_CONST;
#define DACTL_CLI_APPLICATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DACTL_CLI_TYPE_APPLICATION, DactlCLIApplicationPrivate))
enum  {
	DACTL_CLI_APPLICATION_DUMMY_PROPERTY,
	DACTL_CLI_APPLICATION_ADMIN,
	DACTL_CLI_APPLICATION_MODEL,
	DACTL_CLI_APPLICATION_VIEW,
	DACTL_CLI_APPLICATION_CONTROLLER,
	DACTL_CLI_APPLICATION_PLUGINS
};
DactlCLIApplication* dactl_cli_application_get_default (void);
static DactlCLIApplication* __lambda4_ (void);
DactlCLIApplication* dactl_cli_application_new (void);
DactlCLIApplication* dactl_cli_application_construct (GType object_type);
static gpointer ___lambda4__gthread_func (gpointer self);
void dactl_cli_application_set_plugins (DactlCLIApplication* self, GeeArrayList* value);
static void dactl_cli_application_real_register_plugin (DactlApplication* base, DactlPlugin* plugin);
gint dactl_cli_application_launch (DactlCLIApplication* self, gchar** args, int args_length1);
static gint dactl_cli_application_real_launch (DactlCLIApplication* self, gchar** args, int args_length1);
gboolean dactl_cli_application_get_admin (DactlCLIApplication* self);
void dactl_cli_application_set_admin (DactlCLIApplication* self, gboolean value);
DactlApplicationModel* dactl_cli_application_get_model (DactlCLIApplication* self);
void dactl_cli_application_set_model (DactlCLIApplication* self, DactlApplicationModel* value);
DactlApplicationView* dactl_cli_application_get_view (DactlCLIApplication* self);
void dactl_cli_application_set_view (DactlCLIApplication* self, DactlApplicationView* value);
DactlApplicationController* dactl_cli_application_get_controller (DactlCLIApplication* self);
void dactl_cli_application_set_controller (DactlCLIApplication* self, DactlApplicationController* value);
GeeArrayList* dactl_cli_application_get_plugins (DactlCLIApplication* self);
static void dactl_cli_application_finalize (GObject* obj);
static void _vala_dactl_cli_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_dactl_cli_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
     * Instantiate a new command line application.
     *
     * @return Instance of the application.
     */
static DactlCLIApplication* __lambda4_ (void) {
	DactlCLIApplication* result = NULL;
	DactlCLIApplication* _tmp0_ = NULL;
	_tmp0_ = dactl_cli_application_new ();
	result = _tmp0_;
	return result;
}


static gpointer ___lambda4__gthread_func (gpointer self) {
	gpointer result;
	result = __lambda4_ ();
	return result;
}


DactlCLIApplication* dactl_cli_application_get_default (void) {
	DactlCLIApplication* result = NULL;
	gconstpointer _tmp0_ = NULL;
	_tmp0_ = g_once (&dactl_cli_application__instance, ___lambda4__gthread_func, NULL);
	result = (DactlCLIApplication*) _tmp0_;
	return result;
}


DactlCLIApplication* dactl_cli_application_construct (GType object_type) {
	DactlCLIApplication * self = NULL;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	g_debug ("dactl-cli-application.vala:52: CLI application construction");
	self = (DactlCLIApplication*) g_object_new (object_type, "application-id", "org.coanda.dactl.cli", "flags", G_APPLICATION_HANDLES_COMMAND_LINE | G_APPLICATION_HANDLES_OPEN, NULL);
	_tmp0_ = gee_array_list_new (DACTL_TYPE_PLUGIN, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_tmp1_ = _tmp0_;
	dactl_cli_application_set_plugins (self, _tmp1_);
	_g_object_unref0 (_tmp1_);
	return self;
}


DactlCLIApplication* dactl_cli_application_new (void) {
	return dactl_cli_application_construct (DACTL_CLI_TYPE_APPLICATION);
}


/**
     * {@inheritDoc}
     */
static void dactl_cli_application_real_register_plugin (DactlApplication* base, DactlPlugin* plugin) {
	DactlCLIApplication * self;
	self = (DactlCLIApplication*) base;
	g_return_if_fail (plugin != NULL);
}


/**
     * {@inheritDoc}
     */
static gint dactl_cli_application_real_launch (DactlCLIApplication* self, gchar** args, int args_length1) {
	gint result = 0;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp1_ = g_application_run (G_TYPE_CHECK_INSTANCE_TYPE (self, g_application_get_type ()) ? ((GApplication*) self) : NULL, _tmp0__length1, _tmp0_);
	result = _tmp1_;
	return result;
}


gint dactl_cli_application_launch (DactlCLIApplication* self, gchar** args, int args_length1) {
	g_return_val_if_fail (self != NULL, 0);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->launch (self, args, args_length1);
}


gboolean dactl_cli_application_get_admin (DactlCLIApplication* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->_admin;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_admin (DactlCLIApplication* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_admin = _tmp0_;
	g_object_notify ((GObject *) self, "admin");
}


DactlApplicationModel* dactl_cli_application_get_model (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_model (self);
}


static DactlApplicationModel* dactl_cli_application_real_get_model (DactlCLIApplication* base) {
	DactlApplicationModel* result;
	DactlCLIApplication* self;
	DactlApplicationModel* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_model;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_model (DactlCLIApplication* self, DactlApplicationModel* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_model (self, value);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void dactl_cli_application_real_set_model (DactlCLIApplication* base, DactlApplicationModel* value) {
	DactlCLIApplication* self;
	DactlApplicationModel* _tmp0_ = NULL;
	DactlApplicationModel* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_model);
	self->priv->_model = _tmp1_;
	g_object_notify ((GObject *) self, "model");
}


DactlApplicationView* dactl_cli_application_get_view (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_view (self);
}


static DactlApplicationView* dactl_cli_application_real_get_view (DactlCLIApplication* base) {
	DactlApplicationView* result;
	DactlCLIApplication* self;
	DactlApplicationView* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_view;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_view (DactlCLIApplication* self, DactlApplicationView* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_view (self, value);
}


static void dactl_cli_application_real_set_view (DactlCLIApplication* base, DactlApplicationView* value) {
	DactlCLIApplication* self;
	DactlApplicationView* _tmp0_ = NULL;
	DactlApplicationView* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_view);
	self->priv->_view = _tmp1_;
	g_object_notify ((GObject *) self, "view");
}


DactlApplicationController* dactl_cli_application_get_controller (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_controller (self);
}


static DactlApplicationController* dactl_cli_application_real_get_controller (DactlCLIApplication* base) {
	DactlApplicationController* result;
	DactlCLIApplication* self;
	DactlApplicationController* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_controller;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_controller (DactlCLIApplication* self, DactlApplicationController* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_controller (self, value);
}


static void dactl_cli_application_real_set_controller (DactlCLIApplication* base, DactlApplicationController* value) {
	DactlCLIApplication* self;
	DactlApplicationController* _tmp0_ = NULL;
	DactlApplicationController* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_controller);
	self->priv->_controller = _tmp1_;
	g_object_notify ((GObject *) self, "controller");
}


GeeArrayList* dactl_cli_application_get_plugins (DactlCLIApplication* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return DACTL_CLI_APPLICATION_GET_CLASS (self)->get_plugins (self);
}


static GeeArrayList* dactl_cli_application_real_get_plugins (DactlCLIApplication* base) {
	GeeArrayList* result;
	DactlCLIApplication* self;
	GeeArrayList* _tmp0_ = NULL;
	self = base;
	_tmp0_ = self->priv->_plugins;
	result = _tmp0_;
	return result;
}


void dactl_cli_application_set_plugins (DactlCLIApplication* self, GeeArrayList* value) {
	g_return_if_fail (self != NULL);
	DACTL_CLI_APPLICATION_GET_CLASS (self)->set_plugins (self, value);
}


static void dactl_cli_application_real_set_plugins (DactlCLIApplication* base, GeeArrayList* value) {
	DactlCLIApplication* self;
	GeeArrayList* _tmp0_ = NULL;
	GeeArrayList* _tmp1_ = NULL;
	self = base;
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_plugins);
	self->priv->_plugins = _tmp1_;
	g_object_notify ((GObject *) self, "plugins");
}


static void dactl_cli_application_class_init (DactlCLIApplicationClass * klass) {
	dactl_cli_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DactlCLIApplicationPrivate));
	((DactlCLIApplicationClass *) klass)->launch = dactl_cli_application_real_launch;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_model = dactl_cli_application_real_get_model;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_model = dactl_cli_application_real_set_model;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_view = dactl_cli_application_real_get_view;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_view = dactl_cli_application_real_set_view;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_controller = dactl_cli_application_real_get_controller;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_controller = dactl_cli_application_real_set_controller;
	DACTL_CLI_APPLICATION_CLASS (klass)->get_plugins = dactl_cli_application_real_get_plugins;
	DACTL_CLI_APPLICATION_CLASS (klass)->set_plugins = dactl_cli_application_real_set_plugins;
	G_OBJECT_CLASS (klass)->get_property = _vala_dactl_cli_application_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_dactl_cli_application_set_property;
	G_OBJECT_CLASS (klass)->finalize = dactl_cli_application_finalize;
	/**
	     * Allow administrative functionality
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_ADMIN, g_param_spec_boolean ("admin", "admin", "admin", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_MODEL, g_param_spec_object ("model", "model", "model", DACTL_TYPE_APPLICATION_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_VIEW, g_param_spec_object ("view", "view", "view", DACTL_TYPE_APPLICATION_VIEW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", DACTL_TYPE_APPLICATION_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * {@inheritDoc}
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), DACTL_CLI_APPLICATION_PLUGINS, g_param_spec_object ("plugins", "plugins", "plugins", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * Used when the user requests a configuration save.
	     */
	g_signal_new ("save_requested", DACTL_CLI_TYPE_APPLICATION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void dactl_cli_application_dactl_application_interface_init (DactlApplicationIface * iface) {
	dactl_cli_application_dactl_application_parent_iface = g_type_interface_peek_parent (iface);
	iface->register_plugin = (void (*)(DactlApplication*, DactlPlugin*)) dactl_cli_application_real_register_plugin;
	iface->launch = (gint (*)(DactlApplication*, gchar**, int)) dactl_cli_application_launch;
	iface->get_model = (DactlApplicationModel* (*) (DactlApplication *)) dactl_cli_application_get_model;
	iface->set_model = (void (*) (DactlApplication *, DactlApplicationModel*)) dactl_cli_application_set_model;
	iface->get_view = (DactlApplicationView* (*) (DactlApplication *)) dactl_cli_application_get_view;
	iface->set_view = (void (*) (DactlApplication *, DactlApplicationView*)) dactl_cli_application_set_view;
	iface->get_controller = (DactlApplicationController* (*) (DactlApplication *)) dactl_cli_application_get_controller;
	iface->set_controller = (void (*) (DactlApplication *, DactlApplicationController*)) dactl_cli_application_set_controller;
	iface->get_plugins = (GeeArrayList* (*) (DactlApplication *)) dactl_cli_application_get_plugins;
	iface->set_plugins = (void (*) (DactlApplication *, GeeArrayList*)) dactl_cli_application_set_plugins;
}


static void dactl_cli_application_instance_init (DactlCLIApplication * self) {
	self->priv = DACTL_CLI_APPLICATION_GET_PRIVATE (self);
	self->_admin = FALSE;
}


static void dactl_cli_application_finalize (GObject* obj) {
	DactlCLIApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication);
	_g_object_unref0 (self->priv->_model);
	_g_object_unref0 (self->priv->_view);
	_g_object_unref0 (self->priv->_controller);
	_g_object_unref0 (self->priv->_plugins);
	G_OBJECT_CLASS (dactl_cli_application_parent_class)->finalize (obj);
}


GType dactl_cli_application_get_type (void) {
	static volatile gsize dactl_cli_application_type_id__volatile = 0;
	if (g_once_init_enter (&dactl_cli_application_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DactlCLIApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dactl_cli_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DactlCLIApplication), 0, (GInstanceInitFunc) dactl_cli_application_instance_init, NULL };
		static const GInterfaceInfo dactl_application_info = { (GInterfaceInitFunc) dactl_cli_application_dactl_application_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType dactl_cli_application_type_id;
		dactl_cli_application_type_id = g_type_register_static (g_application_get_type (), "DactlCLIApplication", &g_define_type_info, 0);
		g_type_add_interface_static (dactl_cli_application_type_id, DACTL_TYPE_APPLICATION, &dactl_application_info);
		g_once_init_leave (&dactl_cli_application_type_id__volatile, dactl_cli_application_type_id);
	}
	return dactl_cli_application_type_id__volatile;
}


static void _vala_dactl_cli_application_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	DactlCLIApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication);
	switch (property_id) {
		case DACTL_CLI_APPLICATION_ADMIN:
		g_value_set_boolean (value, dactl_cli_application_get_admin (self));
		break;
		case DACTL_CLI_APPLICATION_MODEL:
		g_value_set_object (value, dactl_cli_application_get_model (self));
		break;
		case DACTL_CLI_APPLICATION_VIEW:
		g_value_set_object (value, dactl_cli_application_get_view (self));
		break;
		case DACTL_CLI_APPLICATION_CONTROLLER:
		g_value_set_object (value, dactl_cli_application_get_controller (self));
		break;
		case DACTL_CLI_APPLICATION_PLUGINS:
		g_value_set_object (value, dactl_cli_application_get_plugins (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_dactl_cli_application_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	DactlCLIApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DACTL_CLI_TYPE_APPLICATION, DactlCLIApplication);
	switch (property_id) {
		case DACTL_CLI_APPLICATION_ADMIN:
		dactl_cli_application_set_admin (self, g_value_get_boolean (value));
		break;
		case DACTL_CLI_APPLICATION_MODEL:
		dactl_cli_application_set_model (self, g_value_get_object (value));
		break;
		case DACTL_CLI_APPLICATION_VIEW:
		dactl_cli_application_set_view (self, g_value_get_object (value));
		break;
		case DACTL_CLI_APPLICATION_CONTROLLER:
		dactl_cli_application_set_controller (self, g_value_get_object (value));
		break;
		case DACTL_CLI_APPLICATION_PLUGINS:
		dactl_cli_application_set_plugins (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



